databases:
  - name: n8ndb
    databaseName: n8ndb
    user: n8ndb
    region: ohio

services:
  - type: web
    name: n8n
    env: docker

    region: ohio
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 10
    envVars:
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8ndb
          property: database
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8ndb
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8ndb
          property: port
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8ndb
          property: password
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8ndb
          property: user
      - key: DB_POSTGRESDB_SCHEMA
        value: public

      - key: DB_TYPE
        value: "postgresdb"
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_PASSWORD
        generateValue: true
      - key: N8N_BASIC_AUTH_USER
        value: "admin"


